data:
  name: PermutedMNIST
  data_dir: ./datasets
  n_tasks: 10
  n_classes: 10
  img_size: 28
  in_channel: 1
  pc_valid: 0.15
model:
  net: mlp256
  n_layers: 2
training:
  method: rs
  extension: der
  scenario: domain # single head output
  optimizer: adam
  reset_optimizer: False
  lr: 0.001
  batch_size: 128
  n_epochs: 20
  out_dir: ./experiment/PermutedMNIST/der
  print_every: 10
  save_every: -1
  model_file: model.pth.tar
replay:
  sample_selection: uniform 
  examples_per_class: 1
  memory_limit: 100
  val_threshold: 0.75
  alpha: 1.0
search:
  method: mcts
  iters: 100
  c_param: 0.1
  action_space: seen_tasks
session:
  seed: 1
  verbose: 0
  keep_checkpoints: no 
  load_checkpoints: yes