data:
    name: MNIST
    data_dir: ./datasets
    n_tasks: 5
    n_classes: 10
    img_size: 28
    in_channel: 1
    pc_valid: 0.0
model:
  net: mlp256
  n_layers: 2
training:
  method: rs
  extension: coreset
  scenario: task
  optimizer: adam
  reset_optimizer: False
  lr: 0.001
  batch_size: 128
  n_epochs: 10
  out_dir: ./experiment_get_fwt
  print_every: 10
  save_every: -1
  model_file: model.pth.tar
replay:
  schedule: ets
  sample_selection: uniform 
  examples_per_class: 1
  memory_limit: 10
search:
  action_space: seen_tasks
session:
  n_runs: 1 #5
  seed: 1
  verbose: 0
  keep_checkpoints: no 
  load_checkpoints: yes